### ISSUE TITLE
Database needs to be seeded with categories

### ISSUE THREAD

**Issue by ElyasAktaou** [YasGuy/expense-tracker-test#1]
Database needs to be seeded with some categories for the app to work.

You can use these categories kindly generated by ChatGPT or create your own.

`db.categories.insertMany([
  {
    "label": "Groceries",
    "color": "#FFEB3B",
    "type": "expense"
  },
  {
    "label": "Dining Out",
    "color": "#FF5722",
    "type": "expense"
  },
  {
    "label": "Rent/Mortgage",
    "color": "#4CAF50",
    "type": "expense"
  },
  {
    "label": "Transportation",
    "color": "#03A9F4",
    "type": "expense"
  },
  {
    "label": "Healthcare",
    "color": "#8BC34A",
    "type": "expense"
  },
  {
    "label": "Entertainment",
    "color": "#9C27B0",
    "type": "expense"
  },
  {
    "label": "Income",
    "color": "#00BCD4",
    "type": "income"
  },
  {
    "label": "Salary",
    "color": "#009688",
    "type": "income"
  },
  {
    "label": "Business Income",
    "color": "#FFC107",
    "type": "income"
  },
  {
    "label": "Investment Income",
    "color": "#FF9800",
    "type": "income"
  }
]);`

**Comment by YasGuy** [comment]
thank you, everything is working well after seeding
